name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Make sure pytest is listed in your requirements.txt
          pip install -r requirements.txt
          pip install -e . 

      - name: Run tests
        run: pytest

      # The autograding action will read the test configuration from .github/classroom/autograding.json
      - name: Autograding
        uses: education/autograding@v1